"use client";

import { useEffect, useState } from "react";
import { BookOpen, LoaderCircle, Save } from "lucide-react";

type Reflection = { id: string; date: string; workedWell: string; tomorrowDependsOn: string };

export default function JournalPage() {
  const [reflections, setReflections] = useState<Reflection[]>([]);
  const [workedWell, setWorkedWell] = useState("");
  const [tomorrowDependsOn, setTomorrowDependsOn] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  useEffect(() => { fetch("/api/journal").then((response) => response.json()).then((data: Reflection[]) => { setReflections(data); const today = data.find((item) => new Date(item.date).toDateString() === new Date().toDateString()); if (today) { setWorkedWell(today.workedWell); setTomorrowDependsOn(today.tomorrowDependsOn); } }); }, []);
  const save = async () => { setSaving(true); setSaved(false); const response = await fetch("/api/journal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workedWell, tomorrowDependsOn }) }); if (response.ok) { const entry = await response.json(); setReflections((current) => [entry, ...current.filter((item) => item.id !== entry.id)]); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } setSaving(false); };
  const hasToday = reflections.some((item) => new Date(item.date).toDateString() === new Date().toDateString());
  return <div className="mx-auto w-full max-w-[1000px] animate-fade-in pb-10"><section className="mb-8 border-b border-[var(--border)] pb-6"><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-[var(--coding)]">Journal / daily review</p><h1>Close the loop.</h1><p className="mt-2 max-w-xl text-sm">Notice what worked, then name the condition that makes tomorrow easier.</p></section><section className="card"><div className="mb-5 flex items-center gap-3"><BookOpen size={19} className="text-[var(--coding)]" /><div><h2 className="text-lg">Today&apos;s reflection</h2><p className="mt-1 text-xs text-[var(--text-muted)]">A short record is enough. Make it honest.</p></div></div><div className="space-y-4"><label className="block text-sm font-semibold">What worked today?<textarea className="textarea mt-2" value={workedWell} onChange={(event) => setWorkedWell(event.target.value)} placeholder="Name the action, choice, or condition that helped." /></label><label className="block text-sm font-semibold">What does tomorrow depend on?<textarea className="textarea mt-2" value={tomorrowDependsOn} onChange={(event) => setTomorrowDependsOn(event.target.value)} placeholder="Name the one thing that makes tomorrow count." /></label></div><div className="mt-5 flex items-center gap-3"><button className="btn btn-primary" onClick={() => void save()} disabled={saving || !workedWell.trim() || !tomorrowDependsOn.trim()}>{saving ? <LoaderCircle size={15} className="animate-spin" /> : <Save size={15} />} {hasToday ? "Update reflection" : "Save reflection"}</button>{saved && <span className="text-sm font-semibold text-[var(--success)]">Saved</span>}</div></section><section className="mt-8"><div className="mb-3 flex items-center justify-between"><h2>Past reflections</h2><span className="text-xs text-[var(--text-muted)]">Last 30</span></div>{reflections.length ? <div className="space-y-3">{reflections.map((reflection) => <article className="card" key={reflection.id}><div className="mb-4 text-xs font-bold uppercase tracking-wider text-[var(--coding)]">{new Date(reflection.date).toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" })}</div><div className="grid gap-4 md:grid-cols-2"><div><h4>What worked</h4><p className="mt-2 whitespace-pre-wrap text-sm">{reflection.workedWell}</p></div><div><h4>Tomorrow depends on</h4><p className="mt-2 whitespace-pre-wrap text-sm">{reflection.tomorrowDependsOn}</p></div></div></article>)}</div> : <div className="card text-sm text-[var(--text-muted)]">Your reflections will appear here.</div>}</section></div>;
}
