"use client";

import Link from "next/link";
import { Check, ChevronRight, LockKeyhole, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";

type Lesson = { id: string; title: string; order: number; completed: boolean; locked: boolean; bestScore: number; previousTitle: string | null };
type Track = { name: string; completed: number; total: number; lessons: Lesson[] };
type Domain = { domain: string; color: string; tracks: Track[] };

export default function LearnPage() {
  const [domains, setDomains] = useState<Domain[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/learn/tracks").then((response) => response.ok ? response.json() : []).then(setDomains).finally(() => setLoading(false)); }, []);
  return <div className="mx-auto w-full max-w-[1200px] animate-fade-in pb-10"><section className="mb-8 border-b border-[var(--border)] pb-6"><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-[var(--study)]">Learn / deliberate practice</p><h1>Build useful knowledge.</h1><p className="mt-2 max-w-xl text-sm">Move through each track in order. Read closely, then prove what stayed with you.</p></section>{loading ? <div className="flex items-center gap-2 text-sm text-[var(--text-muted)]"><LoaderCircle size={16} className="animate-spin" /> Loading lessons...</div> : domains.length ? <div className="space-y-9">{domains.map((domain) => <section key={domain.domain}><div className="mb-4 flex items-center gap-3"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: domain.color }} /><h2>{domain.domain}</h2></div><div className="grid gap-4 lg:grid-cols-2">{domain.tracks.map((track) => <div className="card" key={track.name}><div className="mb-4 flex items-end justify-between"><div><h3>{track.name}</h3><p className="mt-1 text-xs">{track.completed} of {track.total} lessons complete</p></div><span className="text-xs font-bold" style={{ color: domain.color }}>{Math.round(track.completed / track.total * 100)}%</span></div><div className="progress-bar mb-4"><div className="progress-fill" style={{ width: `${track.completed / track.total * 100}%`, backgroundColor: domain.color }} /></div><div className="divide-y divide-[var(--border)]">{track.lessons.map((lesson) => lesson.locked ? <div key={lesson.id} title={`Complete ${lesson.previousTitle} first`} className="flex items-center gap-3 py-3 text-sm text-[var(--text-muted)]"><LockKeyhole size={15} /><span className="min-w-0 flex-1 truncate">{lesson.order}. {lesson.title}</span>{lesson.bestScore >= 0 && <span className="text-xs">Best {lesson.bestScore}%</span>}</div> : <Link key={lesson.id} href={`/learn/${lesson.id}`} className="flex items-center gap-3 py-3 text-sm transition-colors hover:text-[var(--text-primary)]"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-md" style={{ color: lesson.completed ? domain.color : "var(--text-muted)", backgroundColor: lesson.completed ? `${domain.color}18` : "var(--bg-elevated)" }}>{lesson.completed ? <Check size={14} /> : lesson.order}</span><span className="min-w-0 flex-1 truncate">{lesson.title}</span>{lesson.bestScore >= 0 && <span className="text-xs text-[var(--text-muted)]">Best {lesson.bestScore}%</span>}<ChevronRight size={15} className="text-[var(--text-muted)]" /></Link>)}</div></div>)}</div></section>)}</div> : <div className="card text-sm text-[var(--text-muted)]">No lessons have been seeded yet.</div>}</div>;
}
