export interface JsRoadmapItem {
  id: number; // 1 to 154
  moduleNumber: number; // 4, 5, 6, 7, 9, 10
  moduleName: string;
  title: string;
  isQuizOrExercise: boolean;
}

export interface JsDailyScheduleBlock {
  dayNumber: number; // 1 to 14
  moduleName: string;
  mainTopic: string;
  itemRange: string;
  items: string[];
  estimatedMinutes: number;
  quizzes: string[];
  learningTarget: string;
}

export interface ChemistryDailyScheduleBlock {
  dayNumber: number; // 1 to 30
  weekNumber: number; // 1 to 4
  mainTopic: string;
  smallTopics: string[];
  difficulty: 'easy' | 'medium' | 'hard' | 'entrance';
  estimatedMinutes: number;
  isEntrancePriority: boolean;
  practiceTarget: string;
  reviewTarget: string;
  sessionBreakdown: {
    learnMins: number;
    activeRecallMins: number;
    flashcardsMins: number;
    practiceMins: number;
    oldTopicRecallMins: number;
  };
}

export const MASTERY_LEVELS = [
  { level: 1, name: 'Understand', badge: '🌱 Understand', desc: 'Can explain simply in plain words', thresholdAccuracy: 60 },
  { level: 2, name: 'Recall', badge: '🧠 Recall', desc: 'Can recall formulas and definitions without hints', thresholdAccuracy: 70 },
  { level: 3, name: 'Apply', badge: '⚡ Apply', desc: 'Can solve standard problems and write code', thresholdAccuracy: 75 },
  { level: 4, name: 'Mastered', badge: '🏆 Mastered / Entrance', desc: 'Can solve tricky entrance/exam problems with >=80% accuracy', thresholdAccuracy: 80 },
];

// ── 1. EXACT 154 JAVASCRIPT ROADMAP ITEMS (5 MILLION CODERS) ──────────────────
export const JAVASCRIPT_COURSE_NAME = '5 Million Coders / JavaScript';

export const JAVASCRIPT_154_ITEMS: JsRoadmapItem[] = [
  // MODULE 4 — LOOPS (Items 1 to 16)
  { id: 1, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'intro to loops', isQuizOrExercise: false },
  { id: 2, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'while Loops', isQuizOrExercise: false },
  { id: 3, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Parts of a while Loop', isQuizOrExercise: false },
  { id: 4, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: JuliaJames', isQuizOrExercise: true },
  { id: 5, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: 99 Bottles of Juice', isQuizOrExercise: true },
  { id: 6, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Countdown, Liftoff!', isQuizOrExercise: true },
  { id: 7, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'for Loops', isQuizOrExercise: false },
  { id: 8, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'parts of a for Loop', isQuizOrExercise: false },
  { id: 9, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Nested Loops', isQuizOrExercise: false },
  { id: 10, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Operators', isQuizOrExercise: false },
  { id: 11, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Changing the Loop', isQuizOrExercise: true },
  { id: 12, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Fix the Error 1', isQuizOrExercise: true },
  { id: 13, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Fix the Error 2 (4-6)', isQuizOrExercise: true },
  { id: 14, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Factorials! (4-7)', isQuizOrExercise: true },
  { id: 15, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Quiz: Find my Seat (4-8)', isQuizOrExercise: true },
  { id: 16, moduleNumber: 4, moduleName: 'Module 4 — Loops', title: 'Lesson Summary', isQuizOrExercise: false },

  // MODULE 5 — FUNCTIONS (Items 17 to 41)
  { id: 17, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Intro to Functions', isQuizOrExercise: false },
  { id: 18, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Function Example', isQuizOrExercise: false },
  { id: 19, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Declaring Function', isQuizOrExercise: false },
  { id: 20, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Function Recap', isQuizOrExercise: false },
  { id: 21, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Laugh it Off 1', isQuizOrExercise: true },
  { id: 22, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Laugh it Off 2', isQuizOrExercise: true },
  { id: 23, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Return Values', isQuizOrExercise: false },
  { id: 24, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Using Returns Values', isQuizOrExercise: false },
  { id: 25, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Scope', isQuizOrExercise: false },
  { id: 26, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Global and Function Scopes', isQuizOrExercise: false },
  { id: 27, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'The Scope Chain', isQuizOrExercise: false },
  { id: 28, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Block Scope', isQuizOrExercise: false },
  { id: 29, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Scopes Gotcha Shadowing', isQuizOrExercise: false },
  { id: 30, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Scope Recap', isQuizOrExercise: false },
  { id: 31, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Function Expressions', isQuizOrExercise: false },
  { id: 32, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Scope Gotcha 2: Hoisting', isQuizOrExercise: false },
  { id: 33, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'More About Hoisting', isQuizOrExercise: false },
  { id: 34, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Hoisting Recap', isQuizOrExercise: false },
  { id: 35, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Build a Triangle', isQuizOrExercise: true },
  { id: 36, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Patterns with Function Expressions', isQuizOrExercise: false },
  { id: 37, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Function Expression Recap', isQuizOrExercise: false },
  { id: 38, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Laugh', isQuizOrExercise: true },
  { id: 39, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Cry', isQuizOrExercise: true },
  { id: 40, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Quiz: Inline', isQuizOrExercise: true },
  { id: 41, moduleNumber: 5, moduleName: 'Module 5 — Functions', title: 'Lesson Summary', isQuizOrExercise: false },

  // MODULE 6 — ARRAYS (Items 42 to 66)
  { id: 42, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Intro to Arrays', isQuizOrExercise: false },
  { id: 43, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Dounts to Code', isQuizOrExercise: false },
  { id: 44, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Creating an Array', isQuizOrExercise: false },
  { id: 45, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Accessing Array', isQuizOrExercise: false },
  { id: 46, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Accessing Array Elements', isQuizOrExercise: false },
  { id: 47, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Array Index', isQuizOrExercise: false },
  { id: 48, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: UdaciFamily', isQuizOrExercise: true },
  { id: 49, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: Building the Crew', isQuizOrExercise: true },
  { id: 50, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: The price is Right', isQuizOrExercise: true },
  { id: 51, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Array Properties and Methods', isQuizOrExercise: false },
  { id: 52, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Length', isQuizOrExercise: false },
  { id: 53, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Push', isQuizOrExercise: false },
  { id: 54, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Pop', isQuizOrExercise: false },
  { id: 55, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Splice', isQuizOrExercise: false },
  { id: 56, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: Colors Of the Rainbow', isQuizOrExercise: true },
  { id: 57, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: Quidditch out the Docs', isQuizOrExercise: true },
  { id: 58, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Array Loops', isQuizOrExercise: false },
  { id: 59, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'The for Each Loop', isQuizOrExercise: false },
  { id: 60, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: Another Type of Loop', isQuizOrExercise: true },
  { id: 61, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Map', isQuizOrExercise: false },
  { id: 62, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: I Got Bills', isQuizOrExercise: true },
  { id: 63, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Arrays in Arrays', isQuizOrExercise: false },
  { id: 64, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: '2D Donut Arrays', isQuizOrExercise: false },
  { id: 65, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Quiz: Nested Numbers', isQuizOrExercise: true },
  { id: 66, moduleNumber: 6, moduleName: 'Module 6 — Arrays', title: 'Lesson Summary', isQuizOrExercise: false },

  // MODULE 7 — OBJECTS / DOM (Items 67 to 90)
  { id: 67, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Lesson Intro', isQuizOrExercise: false },
  { id: 68, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'The DOM', isQuizOrExercise: false },
  { id: 69, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Exercise: Exploring the DOM', isQuizOrExercise: true },
  { id: 70, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Solution: Exploring the DOM', isQuizOrExercise: false },
  { id: 71, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Recap: The DOM', isQuizOrExercise: false },
  { id: 72, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'CSS Review', isQuizOrExercise: false },
  { id: 73, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Select page Element By ID', isQuizOrExercise: false },
  { id: 74, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Exercise: Document.getElementById()', isQuizOrExercise: true },
  { id: 75, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Solution: Document.getElementById()', isQuizOrExercise: false },
  { id: 76, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Recap: Document.getElementById()', isQuizOrExercise: false },
  { id: 77, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Select Page Elements By Class Or Tag', isQuizOrExercise: false },
  { id: 78, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Quizzes: Select Page Elements BY Class Or Tag', isQuizOrExercise: true },
  { id: 79, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Recaps: Select Page Elements By Class Or Tag', isQuizOrExercise: false },
  { id: 80, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Nodes, Elements, and Interfaces....Oh My!', isQuizOrExercise: false },
  { id: 81, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'The Node Interface', isQuizOrExercise: false },
  { id: 82, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'The Element Interface', isQuizOrExercise: false },
  { id: 83, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Quizzes: Nodes, Elements and Interfaces', isQuizOrExercise: true },
  { id: 84, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'More Interfaces', isQuizOrExercise: false },
  { id: 85, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Recap: Nodes, Elements and Interfaces', isQuizOrExercise: false },
  { id: 86, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'More Ways To Access Elements', isQuizOrExercise: false },
  { id: 87, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'querySelector', isQuizOrExercise: false },
  { id: 88, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'querySelectorAll', isQuizOrExercise: false },
  { id: 89, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Recap: querySelector and querySelectorAll', isQuizOrExercise: false },
  { id: 90, moduleNumber: 7, moduleName: 'Module 7 — Objects / DOM', title: 'Lesson Summary', isQuizOrExercise: false },

  // MODULE 9 — CREATING CONTENT WITH JAVASCRIPT (Items 91 to 120)
  { id: 91, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Introduction', isQuizOrExercise: false },
  { id: 92, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Our Practice Environment', isQuizOrExercise: false },
  { id: 93, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Course Workspace', isQuizOrExercise: false },
  { id: 94, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Update Existing Page Content', isQuizOrExercise: false },
  { id: 95, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'innerHTML', isQuizOrExercise: false },
  { id: 96, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'textContent and innerText', isQuizOrExercise: false },
  { id: 97, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Exercise: Update Program Title', isQuizOrExercise: true },
  { id: 98, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Solution: Update Program Title', isQuizOrExercise: false },
  { id: 99, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Recap: Update Existing Content', isQuizOrExercise: false },
  { id: 100, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Add New Page Content', isQuizOrExercise: false },
  { id: 101, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Create Content with createElement()', isQuizOrExercise: false },
  { id: 102, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Add New Page Content', isQuizOrExercise: false },
  { id: 103, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Create Content with createElement()', isQuizOrExercise: false },
  { id: 104, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Add Content with appendChild()', isQuizOrExercise: false },
  { id: 105, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Create Text Nodes with createTextNode()', isQuizOrExercise: false },
  { id: 106, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Other Ways to Insert HTML', isQuizOrExercise: false },
  { id: 107, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Exercise: Add New Content', isQuizOrExercise: true },
  { id: 108, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Solution: Add Page Content', isQuizOrExercise: false },
  { id: 109, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Remove Page Content', isQuizOrExercise: false },
  { id: 110, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Quizzes: Remove Page Content', isQuizOrExercise: true },
  { id: 111, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Recap: Remove Page Content', isQuizOrExercise: false },
  { id: 112, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Style Page Content', isQuizOrExercise: false },
  { id: 113, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Modify Using the style Property', isQuizOrExercise: false },
  { id: 114, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Access Multiple Styles with cssText', isQuizOrExercise: false },
  { id: 115, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Set Styles With setAttribute', isQuizOrExercise: false },
  { id: 116, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Use className to Access Element Class', isQuizOrExercise: false },
  { id: 117, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Exercise Style Page Content', isQuizOrExercise: true },
  { id: 118, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Solution: Style Page Content', isQuizOrExercise: false },
  { id: 119, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Recap: Style page Content', isQuizOrExercise: false },
  { id: 120, moduleNumber: 9, moduleName: 'Module 9 — Creating Content', title: 'Lesson Summary', isQuizOrExercise: false },

  // MODULE 10 — WORKING WITH BROWSER EVENTS (Items 121 to 154)
  { id: 121, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Introduction', isQuizOrExercise: false },
  { id: 122, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Our Practice Environment', isQuizOrExercise: false },
  { id: 123, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Course Workspace', isQuizOrExercise: false },
  { id: 124, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'What Is an Event?', isQuizOrExercise: false },
  { id: 125, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Event Targets', isQuizOrExercise: false },
  { id: 126, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Listening For Events', isQuizOrExercise: false },
  { id: 127, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Add an Event Listener', isQuizOrExercise: false },
  { id: 128, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Quizzes: Add Event Listeners', isQuizOrExercise: true },
  { id: 129, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'More Events to Listen To', isQuizOrExercise: false },
  { id: 130, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Exercise: Add a Listener', isQuizOrExercise: true },
  { id: 131, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Solution: Add an Event Listener', isQuizOrExercise: false },
  { id: 132, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Recap: Add An Event Listener', isQuizOrExercise: false },
  { id: 133, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'All Done Listening?', isQuizOrExercise: false },
  { id: 134, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Review: Object Equality in JavaScript', isQuizOrExercise: false },
  { id: 135, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Remove An event Listener', isQuizOrExercise: false },
  { id: 136, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Viewing EventListeners', isQuizOrExercise: false },
  { id: 137, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Exercise: Remove an event Listener', isQuizOrExercise: true },
  { id: 138, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Solution: Remove an event Listener', isQuizOrExercise: false },
  { id: 139, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Recap: Remove an event Listener', isQuizOrExercise: false },
  { id: 140, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Phases of an Event', isQuizOrExercise: false },
  { id: 141, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Event Firing Order', isQuizOrExercise: false },
  { id: 142, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Which Phase is Used?', isQuizOrExercise: false },
  { id: 143, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Quizzes: Event Phases', isQuizOrExercise: true },
  { id: 144, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'The Event Object', isQuizOrExercise: false },
  { id: 145, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'The Default Action', isQuizOrExercise: false },
  { id: 146, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Recap: Events', isQuizOrExercise: false },
  { id: 147, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'The Problem of Too Many Events', isQuizOrExercise: false },
  { id: 148, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Event Delegation', isQuizOrExercise: false },
  { id: 149, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Exercise: Add Favorites Buttons', isQuizOrExercise: true },
  { id: 150, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Solution: Add Favorites Buttons', isQuizOrExercise: false },
  { id: 151, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Recap: Add Favorites Buttons', isQuizOrExercise: false },
  { id: 152, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'When Is the DOM Ready?', isQuizOrExercise: false },
  { id: 153, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'DOMContentLoaded', isQuizOrExercise: false },
  { id: 154, moduleNumber: 10, moduleName: 'Module 10 — Browser Events', title: 'Lesson Summary', isQuizOrExercise: false },
];

// ── 2. JAVASCRIPT 14-DAY SCHEDULE DISTRIBUTION ENGINE ─────────────────────────
export const JAVASCRIPT_14_DAY_SCHEDULE: JsDailyScheduleBlock[] = [
  {
    dayNumber: 1,
    moduleName: 'Module 4 — Loops',
    mainTopic: 'While Loops & Counter Fundamentals',
    itemRange: 'Items 1–11',
    items: [
      'intro to loops',
      'while Loops',
      'Parts of a while Loop',
      'Quiz: JuliaJames',
      'Quiz: 99 Bottles of Juice',
      'Quiz: Countdown, Liftoff!',
      'for Loops',
      'parts of a for Loop',
      'Nested Loops',
      'Operators',
      'Quiz: Changing the Loop',
    ],
    estimatedMinutes: 100,
    quizzes: ['Quiz: JuliaJames', 'Quiz: 99 Bottles of Juice', 'Quiz: Countdown, Liftoff!', 'Quiz: Changing the Loop'],
    learningTarget: 'Master loop initialization, conditional checks, loop increments, and nested loop patterns.',
  },
  {
    dayNumber: 2,
    moduleName: 'Module 4 — Loops → Module 5 — Functions',
    mainTopic: 'Loop Errors & Intro to Functions',
    itemRange: 'Items 12–24',
    items: [
      'Quiz: Fix the Error 1',
      'Quiz: Fix the Error 2 (4-6)',
      'Quiz: Factorials! (4-7)',
      'Quiz: Find my Seat (4-8)',
      'Lesson Summary',
      'Intro to Functions',
      'Function Example',
      'Declaring Function',
      'Function Recap',
      'Quiz: Laugh it Off 1',
      'Quiz: Laugh it Off 2',
      'Return Values',
      'Using Returns Values',
    ],
    estimatedMinutes: 110,
    quizzes: ['Quiz: Factorials! (4-7)', 'Quiz: Find my Seat (4-8)', 'Quiz: Laugh it Off 1 & 2'],
    learningTarget: 'Finish all Loops quizzes, debug infinite loops, declare functions, and distinguish return vs console.log.',
  },
  {
    dayNumber: 3,
    moduleName: 'Module 5 — Functions',
    mainTopic: 'Scope, Variable Shadowing & Hoisting',
    itemRange: 'Items 25–35',
    items: [
      'Scope',
      'Global and Function Scopes',
      'The Scope Chain',
      'Block Scope',
      'Scopes Gotcha Shadowing',
      'Scope Recap',
      'Function Expressions',
      'Scope Gotcha 2: Hoisting',
      'More About Hoisting',
      'Hoisting Recap',
      'Quiz: Build a Triangle',
    ],
    estimatedMinutes: 105,
    quizzes: ['Quiz: Build a Triangle'],
    learningTarget: 'Understand lexical scope, the scope chain, variable shadowing, and variable/function hoisting rules.',
  },
  {
    dayNumber: 4,
    moduleName: 'Module 5 — Functions → Module 6 — Arrays',
    mainTopic: 'Function Expressions & Intro to Arrays',
    itemRange: 'Items 36–47',
    items: [
      'Patterns with Function Expressions',
      'Function Expression Recap',
      'Quiz: Laugh',
      'Quiz: Cry',
      'Quiz: Inline',
      'Lesson Summary',
      'Intro to Arrays',
      'Dounts to Code',
      'Creating an Array',
      'Accessing Array',
      'Accessing Array Elements',
      'Array Index',
    ],
    estimatedMinutes: 95,
    quizzes: ['Quiz: Laugh', 'Quiz: Cry', 'Quiz: Inline'],
    learningTarget: 'Master anonymous functions, inline callbacks, array indexing, and element access.',
  },
  {
    dayNumber: 5,
    moduleName: 'Module 6 — Arrays',
    mainTopic: 'Array Methods, Mutators & Splice',
    itemRange: 'Items 48–57',
    items: [
      'Quiz: UdaciFamily',
      'Quiz: Building the Crew',
      'Quiz: The price is Right',
      'Array Properties and Methods',
      'Length',
      'Push',
      'Pop',
      'Splice',
      'Quiz: Colors Of the Rainbow',
      'Quiz: Quidditch out the Docs',
    ],
    estimatedMinutes: 100,
    quizzes: ['Quiz: UdaciFamily', 'Quiz: Building the Crew', 'Quiz: Colors Of the Rainbow', 'Quiz: Quidditch out the Docs'],
    learningTarget: 'Master push, pop, shift, unshift, and in-place array modification using splice().',
  },
  {
    dayNumber: 6,
    moduleName: 'Module 6 — Arrays → Module 7 — Objects / DOM',
    mainTopic: 'forEach, Map, 2D Arrays & DOM Intro',
    itemRange: 'Items 58–71',
    items: [
      'Array Loops',
      'The for Each Loop',
      'Quiz: Another Type of Loop',
      'Map',
      'Quiz: I Got Bills',
      'Arrays in Arrays',
      '2D Donut Arrays',
      'Quiz: Nested Numbers',
      'Lesson Summary',
      'Lesson Intro',
      'The DOM',
      'Exercise: Exploring the DOM',
      'Solution: Exploring the DOM',
      'Recap: The DOM',
    ],
    estimatedMinutes: 110,
    quizzes: ['Quiz: Another Type of Loop', 'Quiz: I Got Bills', 'Quiz: Nested Numbers', 'Exercise: Exploring the DOM'],
    learningTarget: 'Transform collections with forEach and map, handle 2D matrix arrays, and understand the HTML DOM tree.',
  },
  {
    dayNumber: 7,
    moduleName: 'Module 7 — Objects / DOM',
    mainTopic: 'DOM Selection & Node vs Element Interfaces',
    itemRange: 'Items 72–82',
    items: [
      'CSS Review',
      'Select page Element By ID',
      'Exercise: Document.getElementById()',
      'Solution: Document.getElementById()',
      'Recap: Document.getElementById()',
      'Select Page Elements By Class Or Tag',
      'Quizzes: Select Page Elements BY Class Or Tag',
      'Recaps: Select Page Elements By Class Or Tag',
      'Nodes, Elements, and Interfaces....Oh My!',
      'The Node Interface',
      'The Element Interface',
    ],
    estimatedMinutes: 100,
    quizzes: ['Exercise: Document.getElementById()', 'Quizzes: Select Page Elements BY Class Or Tag'],
    learningTarget: 'Select page nodes by ID, tag, and class; distinguish between Node and Element interfaces.',
  },
  {
    dayNumber: 8,
    moduleName: 'Module 7 — Objects / DOM → Module 9 — Content',
    mainTopic: 'querySelector, querySelectorAll & Page Updates',
    itemRange: 'Items 83–94',
    items: [
      'Quizzes: Nodes, Elements and Interfaces',
      'More Interfaces',
      'Recap: Nodes, Elements and Interfaces',
      'More Ways To Access Elements',
      'querySelector',
      'querySelectorAll',
      'Recap: querySelector and querySelectorAll',
      'Lesson Summary',
      'Introduction',
      'Our Practice Environment',
      'Course Workspace',
      'Update Existing Page Content',
    ],
    estimatedMinutes: 100,
    quizzes: ['Quizzes: Nodes, Elements and Interfaces', 'Recap: querySelector and querySelectorAll'],
    learningTarget: 'Use querySelector/querySelectorAll with CSS selectors and inspect live DOM collections.',
  },
  {
    dayNumber: 9,
    moduleName: 'Module 9 — Creating Content with JavaScript',
    mainTopic: 'innerHTML, textContent & createElement()',
    itemRange: 'Items 95–106',
    items: [
      'innerHTML',
      'textContent and innerText',
      'Exercise: Update Program Title',
      'Solution: Update Program Title',
      'Recap: Update Existing Content',
      'Add New Page Content',
      'Create Content with createElement()',
      'Add New Page Content',
      'Create Content with createElement()',
      'Add Content with appendChild()',
      'Create Text Nodes with createTextNode()',
      'Other Ways to Insert HTML',
    ],
    estimatedMinutes: 105,
    quizzes: ['Exercise: Update Program Title', 'Exercise: Add New Content'],
    learningTarget: 'Dynamically create HTML elements with createElement(), appendChild(), and textContent.',
  },
  {
    dayNumber: 10,
    moduleName: 'Module 9 — Creating Content with JavaScript',
    mainTopic: 'Element Removal & Dynamic Styling (cssText, setAttribute)',
    itemRange: 'Items 107–120',
    items: [
      'Exercise: Add New Content',
      'Solution: Add Page Content',
      'Remove Page Content',
      'Quizzes: Remove Page Content',
      'Recap: Remove Page Content',
      'Style Page Content',
      'Modify Using the style Property',
      'Access Multiple Styles with cssText',
      'Set Styles With setAttribute',
      'Use className to Access an Element\'s Class',
      'Exercise Style Page Content',
      'Solution: Style Page Content',
      'Recap: Style page Content',
      'Lesson Summary',
    ],
    estimatedMinutes: 105,
    quizzes: ['Quizzes: Remove Page Content', 'Exercise Style Page Content'],
    learningTarget: 'Remove child elements, apply inline styles via cssText, and manage classes dynamically.',
  },
  {
    dayNumber: 11,
    moduleName: 'Module 10 — Working with Browser Events',
    mainTopic: 'Event Targets & Adding Event Listeners',
    itemRange: 'Items 121–132',
    items: [
      'Introduction',
      'Our Practice Environment',
      'Course Workspace',
      'What Is an Event?',
      'Event Targets',
      'Listening For Events',
      'Add an Event Listener',
      'Quizzes: Add Event Listeners',
      'More Events to Listen To',
      'Exercise: Add a Listener',
      'Solution: Add an Event Listener',
      'Recap: Add An Event Listener',
    ],
    estimatedMinutes: 100,
    quizzes: ['Quizzes: Add Event Listeners', 'Exercise: Add a Listener'],
    learningTarget: 'Attach click, input, and keyboard event listeners using addEventListener().',
  },
  {
    dayNumber: 12,
    moduleName: 'Module 10 — Working with Browser Events',
    mainTopic: 'Removing Listeners & Event Phases (Capturing/Bubbling)',
    itemRange: 'Items 133–143',
    items: [
      'All Done Listening?',
      'Review: Object Equality in JavaScript',
      'Remove An event Listener',
      'Viewing EventListeners',
      'Exercise: Remove an event Listener',
      'Solution: Remove an event Listener',
      'Recap: Remove an event Listener',
      'Phases of an Event',
      'Event Firing Order',
      'Which Phase is Used?',
      'Quizzes: Event Phases',
    ],
    estimatedMinutes: 105,
    quizzes: ['Exercise: Remove an event Listener', 'Quizzes: Event Phases'],
    learningTarget: 'Understand function reference equality for removeEventListener and master event bubbling phases.',
  },
  {
    dayNumber: 13,
    moduleName: 'Module 10 — Working with Browser Events',
    mainTopic: 'Event Delegation & DOMContentLoaded',
    itemRange: 'Items 144–154',
    items: [
      'The Event Object',
      'The Default Action',
      'Recap: Events',
      'The Problem of Too Many Events',
      'Event Delegation',
      'Exercise: Add Favorites Buttons',
      'Solution: Add Favorites Buttons',
      'Recap: Add Favorites Buttons',
      'When Is the DOM Ready?',
      'DOMContentLoaded',
      'Lesson Summary',
    ],
    estimatedMinutes: 110,
    quizzes: ['Exercise: Add Favorites Buttons', 'Quiz: Event Delegation'],
    learningTarget: 'Implement performant event delegation on parent containers and hook DOMContentLoaded lifecycle.',
  },
  {
    dayNumber: 14,
    moduleName: '5 Million Coders — Comprehensive Capstone',
    mainTopic: 'DOM & Event Architecture Integration Review',
    itemRange: 'All 154 Items Review',
    items: [
      'Complete Roadmap Synthesis',
      '5 Million Coders Final Assessment Quizzes',
      'Interactive DOM Web Application Project',
      'Performance Optimization & Event Delegation Mastery',
    ],
    estimatedMinutes: 120,
    quizzes: ['Final Comprehensive JavaScript Assessment'],
    learningTarget: 'Synthesize all 154 roadmap items into production-grade interactive DOM web applications.',
  },
];

// ── 3. EXACT 30-DAY CONNECTED CHEMISTRY ROADMAP SCHEDULE ─────────────────────
export const CHEMISTRY_30_DAY_SCHEDULE: ChemistryDailyScheduleBlock[] = [
  {
    dayNumber: 1,
    weekNumber: 1,
    mainTopic: 'Chemistry Basics & Classification of Matter',
    smallTopics: ['Chemistry and Its Importance', 'States of Matter', 'Physical vs Chemical Properties', 'Pure Substances vs Mixtures', 'Separation Techniques'],
    difficulty: 'easy',
    estimatedMinutes: 75,
    isEntrancePriority: false,
    practiceTarget: '15 Classification & Separation Problems',
    reviewTarget: 'Phase diagram definitions & homogeneous vs heterogeneous mixtures',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 2,
    weekNumber: 1,
    mainTopic: 'Measurements & SI Base Units',
    smallTopics: ['Physical Quantities', 'SI Units & Base Units', 'SI Symbols & Derived Units', 'Prefixes & Dimensional Analysis', 'Significant Figures & Precision'],
    difficulty: 'easy',
    estimatedMinutes: 70,
    isEntrancePriority: false,
    practiceTarget: '20 Unit conversion & scientific notation drills',
    reviewTarget: 'Prefix multipliers (nano to giga) & temperature conversions (K, °C)',
    sessionBreakdown: { learnMins: 30, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 3,
    weekNumber: 1,
    mainTopic: 'Atomic Structure & Historical Models',
    smallTopics: ['Dalton, Thomson & Rutherford Models', 'Bohr Model of the Hydrogen Atom', 'Protons, Neutrons & Electrons', 'Atomic Number (Z) & Mass Number (A)', 'Nuclear Symbols'],
    difficulty: 'easy',
    estimatedMinutes: 75,
    isEntrancePriority: false,
    practiceTarget: '15 Subatomic particle counting & nuclear notation exercises',
    reviewTarget: 'Rutherford alpha-scattering experiment implications',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 4,
    weekNumber: 1,
    mainTopic: 'Isotopes, Isobars & Relative Atomic Mass',
    smallTopics: ['Isotopes & Fractional Abundances', 'Isobars & Isotones', 'Mass Spectrometry Basics', 'Average Atomic Mass Calculations', 'Nuclear Stability'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '15 Isotope abundance & average mass mathematical problems',
    reviewTarget: 'Weighted average formula for relative atomic mass',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 5,
    weekNumber: 1,
    mainTopic: 'Quantum Numbers & Electron Orbitals',
    smallTopics: ['Principal, Angular, Magnetic & Spin Quantum Numbers', 'Orbital Shapes (s, p, d, f)', 'Aufbau Principle', 'Pauli Exclusion Principle', 'Hund’s Rule of Maximum Multiplicity'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '20 Electron configuration & orbital box diagram problems',
    reviewTarget: 'Chromium and Copper configuration anomalies',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 6,
    weekNumber: 1,
    mainTopic: 'The Periodic Table & Periodic Trends',
    smallTopics: ['Modern Periodic Law', 'Groups & Periods', 'Atomic & Ionic Radius Trends', 'First & Successive Ionization Energies', 'Electronegativity & Electron Affinity'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '20 Periodic trend ranking & entrance comparison questions',
    reviewTarget: 'Shielding effect & effective nuclear charge (Zeff)',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 7,
    weekNumber: 1,
    mainTopic: 'Valence Electrons & Lewis Dot Structures',
    smallTopics: ['Valence Shell Electrons', 'Octet & Duet Rules', 'Lewis Symbols for Atoms and Ions', 'Formal Charge Calculation', 'Resonance Structures & Octet Exceptions'],
    difficulty: 'easy',
    estimatedMinutes: 75,
    isEntrancePriority: false,
    practiceTarget: '15 Lewis dot structure drawing & formal charge calculations',
    reviewTarget: 'Incomplete and expanded octet examples (BF3, SF6, PCl5)',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 8,
    weekNumber: 2,
    mainTopic: 'Chemical Bonding (Ionic, Covalent & Metallic)',
    smallTopics: ['Ionic Bonding & Lattice Energy', 'Born-Haber Cycle Basics', 'Covalent Single, Double & Triple Bonds', 'Polar vs Non-polar Covalent Bonds', 'Metallic Bonding & Electron Sea Model'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '20 Bond polarity, electronegativity difference & lattice energy problems',
    reviewTarget: 'Properties of ionic vs covalent vs metallic networks',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 9,
    weekNumber: 2,
    mainTopic: 'Molecular Geometry & VSEPR Theory',
    smallTopics: ['VSEPR Theory Principles', 'Electron Geometry vs Molecular Shape', 'Linear, Trigonal Planar, Tetrahedral', 'Trigonal Bipyramidal & Octahedral Shapes', 'Bond Angles & Molecular Polarity (Dipole Moment)'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '20 Molecular shape prediction & net dipole moment evaluations',
    reviewTarget: 'Lone pair repulsion effects on bond angles (CH4 vs NH3 vs H2O)',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 10,
    weekNumber: 2,
    mainTopic: 'Molecules, Compounds & Intermolecular Forces',
    smallTopics: ['IUPAC Inorganic Nomenclature', 'Polyatomic Ions & Formulas', 'London Dispersion Forces', 'Dipole-Dipole Interactions', 'Hydrogen Bonding & Boiling Point Trends'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '20 Compound naming & intermolecular force strength comparisons',
    reviewTarget: 'Anomalous properties of water due to hydrogen bonding',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 11,
    weekNumber: 2,
    mainTopic: 'Chemical Reactions & Balancing Equations',
    smallTopics: ['Law of Conservation of Mass', 'Writing Chemical Equations', 'Balancing Equations by Inspection', 'State Symbols (s, l, g, aq)', 'Reaction Conditions & Catalysts'],
    difficulty: 'easy',
    estimatedMinutes: 75,
    isEntrancePriority: false,
    practiceTarget: '25 Equation balancing drills from basic to complex combustion',
    reviewTarget: 'Conservation of atoms and charge in reactions',
    sessionBreakdown: { learnMins: 30, activeRecallMins: 10, flashcardsMins: 10, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 12,
    weekNumber: 2,
    mainTopic: 'Types of Chemical Reactions & Net Ionic Equations',
    smallTopics: ['Synthesis & Decomposition', 'Single & Double Displacement', 'Combustion Reactions', 'Precipitation & Solubility Rules', 'Complete vs Net Ionic Equations'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '20 Precipitation prediction & net ionic equation derivations',
    reviewTarget: 'Solubility rules (NAG SAG mnemonic: Nitrates, Acetates, Group 1, Sulfates, Ammonium, Group 17)',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 13,
    weekNumber: 2,
    mainTopic: 'The Mole Concept & Molar Mass',
    smallTopics: ['Avogadro’s Number (6.022 × 10²³)', 'Molar Mass of Elements & Compounds', 'Mole-to-Mass & Mass-to-Mole Conversions', 'Percent Composition by Mass', 'Empirical vs Molecular Formula Derivations'],
    difficulty: 'medium',
    estimatedMinutes: 90,
    isEntrancePriority: false,
    practiceTarget: '20 Empirical/molecular formula & mole calculation problems',
    reviewTarget: 'Steps to derive empirical formula from percentage composition',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 14,
    weekNumber: 2,
    mainTopic: 'Stoichiometry I — Mole Ratios & Mass Calculations',
    smallTopics: ['Mole Ratios from Balanced Equations', 'Mole-to-Mole Stoichiometry', 'Mass-to-Mass Conversions', 'Volume Stoichiometry for Gases at STP (22.4 L/mol)', 'Theoretical Yield Calculations'],
    difficulty: 'entrance',
    estimatedMinutes: 100,
    isEntrancePriority: true,
    practiceTarget: '25 Multi-step stoichiometric conversion problems',
    reviewTarget: 'Mass-to-mole bridge diagram & conversion roadmap',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 15,
    weekNumber: 3,
    mainTopic: 'Stoichiometry II — Limiting Reactants & Percent Yield',
    smallTopics: ['Identifying Limiting vs Excess Reactants', 'Calculating Amount of Excess Reactant Left Over', 'Theoretical vs Actual Yield', 'Percent Yield Calculations', 'Consecutive & Sequential Reactions'],
    difficulty: 'entrance',
    estimatedMinutes: 105,
    isEntrancePriority: true,
    practiceTarget: '20 Tricky entrance-level limiting reactant & percent yield problems',
    reviewTarget: 'Systematic 3-step limiting reactant identification algorithm',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 30, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 16,
    weekNumber: 3,
    mainTopic: 'Solutions, Concentration & Dilutions',
    smallTopics: ['Solute, Solvent & Solution', 'Molarity (M) & Molality (m)', 'Mass Percent & ppm/ppb', 'Dilution Formula (M₁V₁ = M₂V₂)', 'Solution Stoichiometry & Titration Basics'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '20 Solution preparation, dilution & molarity problems',
    reviewTarget: 'Difference between molarity (temp dependent) and molality',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 17,
    weekNumber: 3,
    mainTopic: 'Acids, Bases & pH Calculations',
    smallTopics: ['Arrhenius, Brønsted-Lowry & Lewis Acid-Base Definitions', 'Conjugate Acid-Base Pairs', 'Autoionization of Water & Kw (1.0 × 10⁻¹⁴)', 'pH, pOH, [H⁺], [OH⁻] Relationships', 'Strong Acids & Strong Bases Calculations'],
    difficulty: 'hard',
    estimatedMinutes: 95,
    isEntrancePriority: true,
    practiceTarget: '20 Logarithmic pH/pOH calculation and conjugate pair problems',
    reviewTarget: 'The 7 strong acids and strong bases list',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 18,
    weekNumber: 3,
    mainTopic: 'Weak Acids, Ka, Kb & Buffer Systems',
    smallTopics: ['Weak Acid Dissociation Constant (Ka)', 'Weak Base Constant (Kb)', 'Percent Ionization', 'Common Ion Effect', 'Buffer Solutions & Henderson-Hasselbalch Equation'],
    difficulty: 'entrance',
    estimatedMinutes: 105,
    isEntrancePriority: true,
    practiceTarget: '15 ICE-table Ka/Kb equilibrium and buffer pH problems',
    reviewTarget: 'Henderson-Hasselbalch equation and buffer capacity conditions',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 19,
    weekNumber: 3,
    mainTopic: 'Chemical Equilibrium & Equilibrium Constant (Kc, Kp)',
    smallTopics: ['Concept of Dynamic Equilibrium', 'Law of Mass Action & Equilibrium Expressions', 'Calculating Kc from Equilibrium Concentrations', 'Relationship between Kc and Kp (Kp = Kc(RT)^Δn)', 'Reaction Quotient (Q) vs K'],
    difficulty: 'entrance',
    estimatedMinutes: 100,
    isEntrancePriority: true,
    practiceTarget: '20 Reaction quotient comparison & equilibrium constant drills',
    reviewTarget: 'Rules for manipulating K (reversing reaction, multiplying coefficients)',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 20,
    weekNumber: 3,
    mainTopic: 'Le Chatelier’s Principle & ICE Tables',
    smallTopics: ['Effect of Concentration Changes', 'Effect of Pressure & Volume Changes on Gas Equilibria', 'Effect of Temperature on Exothermic vs Endothermic Equilibria', 'Catalyst Effect (Rate vs Equilibrium)', 'Solving Complex ICE Tables'],
    difficulty: 'entrance',
    estimatedMinutes: 105,
    isEntrancePriority: true,
    practiceTarget: '20 Le Chatelier shift predictions & quadratic ICE calculations',
    reviewTarget: 'Temperature is the ONLY factor that changes the numerical value of K',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 30, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 21,
    weekNumber: 3,
    mainTopic: 'Reaction Rates & Collision Theory',
    smallTopics: ['Definition of Reaction Rate', 'Average vs Instantaneous Rates', 'Collision Theory Requirements (Orientation & Energy)', 'Factors Affecting Reaction Rates (Surface area, Conc, Temp, Catalyst)', 'Catalysts & Alternate Reaction Pathways'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '20 Rate graph interpretations & collision frequency questions',
    reviewTarget: 'Maxwell-Boltzmann distribution curves at different temperatures',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 22,
    weekNumber: 4,
    mainTopic: 'Rate Laws, Reaction Order & Activation Energy',
    smallTopics: ['Differential Rate Laws & Rate Constant (k)', 'Reaction Orders (0th, 1st, 2nd order)', 'Method of Initial Rates', 'Integrated Rate Laws & Half-Life', 'Arrhenius Equation & Activation Energy (Ea)'],
    difficulty: 'entrance',
    estimatedMinutes: 95,
    isEntrancePriority: true,
    practiceTarget: '15 Rate law determination from experimental table data',
    reviewTarget: 'Units of rate constant k for different overall orders',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 23,
    weekNumber: 4,
    mainTopic: 'Thermochemistry, Enthalpy & Hess’s Law',
    smallTopics: ['Endothermic vs Exothermic Reactions', 'Enthalpy (ΔH) & Calorimetry (q = mcΔT)', 'Standard Enthalpy of Formation (ΔHf°)', 'Hess’s Law of Heat Summation', 'Bond Enthalpy Calculations'],
    difficulty: 'hard',
    estimatedMinutes: 90,
    isEntrancePriority: true,
    practiceTarget: '20 Hess’s law cycle calculations & calorimetry problems',
    reviewTarget: 'ΔH_rxn = ΣΔHf°(products) - ΣΔHf°(reactants)',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 24,
    weekNumber: 4,
    mainTopic: 'Redox Reactions & Oxidation Numbers',
    smallTopics: ['Oxidation & Reduction Definitions (OIL RIG)', 'Rules for Assigning Oxidation Numbers', 'Identifying Oxidizing and Reducing Agents', 'Disproportionation Reactions', 'Spectator Ions in Redox'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '25 Oxidation number assignments and agent identification drills',
    reviewTarget: 'Special oxidation states of Oxygen (peroxides) and Hydrogen (hydrides)',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 25,
    weekNumber: 4,
    mainTopic: 'Balancing Redox Equations (Ion-Electron Method)',
    smallTopics: ['Half-Reaction Method in Acidic Solution', 'Half-Reaction Method in Basic Solution', 'Conservation of Mass & Charge in Redox', 'Permanganate & Dichromate Redox Titrations', 'Redox Stoichiometry'],
    difficulty: 'hard',
    estimatedMinutes: 95,
    isEntrancePriority: true,
    practiceTarget: '15 Balancing acidic and basic redox half-reaction problems',
    reviewTarget: 'Systematic 5-step ion-electron balancing procedure in acid and base',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 15, flashcardsMins: 10, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 26,
    weekNumber: 4,
    mainTopic: 'Electrochemistry I — Galvanic Cells & Standard Potentials',
    smallTopics: ['Galvanic / Voltaic Cells & Daniell Cell', 'Anode (Oxidation) & Cathode (Reduction)', 'Salt Bridge Function', 'Standard Hydrogen Electrode (SHE)', 'Standard Reduction Potentials & E°cell Calculation'],
    difficulty: 'entrance',
    estimatedMinutes: 100,
    isEntrancePriority: true,
    practiceTarget: '20 Cell notation, electron flow direction & E°cell calculations',
    reviewTarget: 'E°cell = E°cathode - E°anode (standard reduction potentials)',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 20, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 27,
    weekNumber: 4,
    mainTopic: 'Electrochemistry II — Nernst Equation & Electrolysis',
    smallTopics: ['Spontaneity Criteria (ΔG° = -nFE°cell)', 'Nernst Equation for Non-Standard Concentrations', 'Electrolytic Cells vs Galvanic Cells', 'Faraday’s Laws of Electrolysis', 'Electroplating Calculations (q = It)'],
    difficulty: 'entrance',
    estimatedMinutes: 105,
    isEntrancePriority: true,
    practiceTarget: '15 Nernst equation calculations & electroplating quantitative problems',
    reviewTarget: 'Relationship between E°cell, ΔG°, and equilibrium constant K',
    sessionBreakdown: { learnMins: 45, activeRecallMins: 15, flashcardsMins: 15, practiceMins: 25, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 28,
    weekNumber: 4,
    mainTopic: 'Organic Chemistry — Hydrocarbons & Functional Groups',
    smallTopics: ['Homologous Series of Alkanes, Alkenes, Alkynes', 'IUPAC Nomenclature for Branched Hydrocarbons', 'Structural & Geometric Isomerism (cis/trans)', 'Functional Groups (Alcohols, Aldehydes, Ketones, Carboxylic acids)', 'Addition & Substitution Reactions'],
    difficulty: 'medium',
    estimatedMinutes: 85,
    isEntrancePriority: false,
    practiceTarget: '25 Organic IUPAC naming and functional group identification drills',
    reviewTarget: 'Markovnikov’s rule for alkene addition reactions',
    sessionBreakdown: { learnMins: 40, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 29,
    weekNumber: 4,
    mainTopic: 'Industrial Chemistry, Polymers & Materials',
    smallTopics: ['Haber Process for Ammonia Synthesis', 'Contact Process for Sulfuric Acid', 'Addition vs Condensation Polymerization', 'Plastics, Thermoplastics & Thermosetting Polymers', 'Green Chemistry Principles & Catalysis'],
    difficulty: 'medium',
    estimatedMinutes: 80,
    isEntrancePriority: false,
    practiceTarget: '20 Industrial reaction condition & polymer identification questions',
    reviewTarget: 'Optimal pressure and temperature tradeoffs in industrial equilibria',
    sessionBreakdown: { learnMins: 35, activeRecallMins: 10, flashcardsMins: 15, practiceMins: 15, oldTopicRecallMins: 5 },
  },
  {
    dayNumber: 30,
    weekNumber: 4,
    mainTopic: 'Environmental Chemistry & Full Comprehensive Synthesis',
    smallTopics: ['Atmospheric Chemistry & Ozone Depletion', 'Greenhouse Effect & Climate Impacts', 'Acid Rain Formation & Neutralization', 'Water Purification & Treatment', 'Comprehensive 30-Day Entrance Synthesis Exam'],
    difficulty: 'entrance',
    estimatedMinutes: 120,
    isEntrancePriority: true,
    practiceTarget: '50-Question Full Comprehensive Entrance Simulation Exam',
    reviewTarget: 'Complete 30-day concept map and error tag audit',
    sessionBreakdown: { learnMins: 30, activeRecallMins: 20, flashcardsMins: 20, practiceMins: 45, oldTopicRecallMins: 5 },
  },
];

// ── 4. PACING & DEADLINE CALCULATORS ──────────────────────────────────────────

/**
 * Calculates current JavaScript 14-day progress and pace status.
 */
export function calculateJavaScriptPacing(masteredItemIds: (string | number)[]) {
  const totalItems = JAVASCRIPT_154_ITEMS.length; // 154
  const completedCount = masteredItemIds.length;
  const percentage = Math.round((completedCount / totalItems) * 100);

  // Compute current day of schedule (1 to 14)
  // Approximate 11 items per day
  const currentDayIndex = Math.min(14, Math.max(1, Math.floor(completedCount / 11) + 1));
  const currentDaySchedule = JAVASCRIPT_14_DAY_SCHEDULE[currentDayIndex - 1] || JAVASCRIPT_14_DAY_SCHEDULE[0];
  const tomorrowDaySchedule = JAVASCRIPT_14_DAY_SCHEDULE[Math.min(13, currentDayIndex)] || JAVASCRIPT_14_DAY_SCHEDULE[13];

  const daysRemaining = Math.max(1, 14 - currentDayIndex + 1);
  const remainingItems = Math.max(0, totalItems - completedCount);
  const requiredItemsPerDay = Math.ceil(remainingItems / daysRemaining);

  // Pace status: If current progress is behind target day expectations
  const expectedItemsDoneByNow = (currentDayIndex - 1) * 11;
  const isBehind = completedCount < expectedItemsDoneByNow;

  return {
    dayNumber: currentDayIndex,
    totalDays: 14,
    formattedDay: `Day ${currentDayIndex} / 14`,
    completedCount,
    totalItems,
    percentage,
    daysRemaining,
    requiredItemsPerDay,
    isBehind,
    statusText: isBehind ? '⚠️ BEHIND SCHEDULE' : '🟢 ON TRACK',
    catchUpWorkload: isBehind ? `Need ${requiredItemsPerDay} items/day to finish in ${daysRemaining} days` : 'Pacing on target',
    currentLesson: {
      id: `js-day-${currentDayIndex}`,
      title: `${currentDaySchedule.moduleName}: ${currentDaySchedule.mainTopic}`,
      module: currentDaySchedule.moduleName,
      mainTopic: currentDaySchedule.mainTopic,
      itemRange: currentDaySchedule.itemRange,
      subtopics: currentDaySchedule.items,
      quizzes: currentDaySchedule.quizzes,
      targetMinutes: currentDaySchedule.estimatedMinutes,
      learningTarget: currentDaySchedule.learningTarget,
    },
    tomorrowLesson: {
      title: `${tomorrowDaySchedule.moduleName}: ${tomorrowDaySchedule.mainTopic}`,
      module: tomorrowDaySchedule.moduleName,
      mainTopic: tomorrowDaySchedule.mainTopic,
      subtopics: tomorrowDaySchedule.items,
      targetMinutes: tomorrowDaySchedule.estimatedMinutes,
    },
  };
}

/**
 * Calculates current Chemistry 30-day (1-month) progress and pace status.
 */
export function calculateChemistryOneMonthPlan(masteredTopicIds: string[]) {
  const totalDays = CHEMISTRY_30_DAY_SCHEDULE.length; // 30
  const completedCount = masteredTopicIds.length;
  const percentage = Math.round((completedCount / totalDays) * 100);

  const currentDayIndex = Math.min(30, Math.max(1, completedCount + 1));
  const currentDaySchedule = CHEMISTRY_30_DAY_SCHEDULE[currentDayIndex - 1] || CHEMISTRY_30_DAY_SCHEDULE[0];
  const tomorrowDaySchedule = CHEMISTRY_30_DAY_SCHEDULE[Math.min(29, currentDayIndex)] || CHEMISTRY_30_DAY_SCHEDULE[29];

  const daysRemaining = Math.max(1, 30 - currentDayIndex + 1);
  const remainingTopics = Math.max(0, totalDays - completedCount);
  const requiredTopicsPerDay = Math.max(1, Math.ceil(remainingTopics / daysRemaining));

  const expectedDoneByNow = currentDayIndex - 1;
  const isBehind = completedCount < expectedDoneByNow;

  return {
    dayNumber: currentDayIndex,
    totalDays: 30,
    formattedDay: `Day ${currentDayIndex} / 30`,
    completedCount,
    totalTopics: totalDays,
    percentage,
    daysRemaining,
    requiredTopicsPerDay,
    isBehind,
    statusText: isBehind ? '⚠️ BEHIND SCHEDULE' : '🟢 ON TRACK',
    catchUpWorkload: isBehind ? `Need ${requiredTopicsPerDay} topic/day to finish in ${daysRemaining} days` : 'Pacing on target',
    minutesPerDay: currentDaySchedule.estimatedMinutes,
    currentTopic: {
      id: `chem-day-${currentDayIndex}`,
      name: currentDaySchedule.mainTopic,
      weekNumber: currentDaySchedule.weekNumber,
      subtopics: currentDaySchedule.smallTopics,
      difficulty: currentDaySchedule.difficulty,
      isEntrancePriority: currentDaySchedule.isEntrancePriority,
      practiceTarget: currentDaySchedule.practiceTarget,
      reviewTarget: currentDaySchedule.reviewTarget,
      sessionBreakdown: currentDaySchedule.sessionBreakdown,
    },
    tomorrowTopic: {
      name: tomorrowDaySchedule.mainTopic,
      subtopics: tomorrowDaySchedule.smallTopics,
      targetMinutes: tomorrowDaySchedule.estimatedMinutes,
    },
  };
}

export const CHEMISTRY_ROADMAP = CHEMISTRY_30_DAY_SCHEDULE;
export const JAVASCRIPT_ROADMAP = JAVASCRIPT_14_DAY_SCHEDULE;

